### ISSUE TITLE
Calls http://graphite.host//render?... and fails

### ISSUE THREAD

**Issue by marhel** [aalpern/docker-tessera-simple#1]
Following the example, using docker trying to set up `aalpern/tessera-simple` towards 
`nickstenning/graphite` doesn't work. The Tessera site runs OK, but cannot get any data out of graphite, not even the random data ones.

It seems this is caused by an additional slash being inserted when building the full render-url. This ends up calling http://graphite.host//render?... which returns HTML, and no image, causing an error popup in Tessera.

The GRAPHITE_URL was given on the docker command line without a trailing slash, and it doesn't seem to matter if I have a trailing slash in the Graphite URL on the preferences page, or not.

A quickfix was to remove the slash in the call to 

```
url.path(path + '/render') 
```

in the container fs at /src/tessera/tessera/static/app.js, corresponding to https://github.com/urbanairship/tessera/blob/master/js/models/data/Query.js#L52

**Comment by ehazlett** [comment]
you can also do a manual build and get the latest upstream tessera package.  @aalpern would you mind building and pushing to the hub again to get the fix?  thanks!

**Comment by aalpern** [comment]
Sorry I missed this in December - the notification probably got lost in the flood I get from work usage of github, but I got this one right to my inbox. Go figure. 

I just kicked off a build. I'm also about to set up another Docker image that builds off the `development` branch of tessera, where there's a LOT of new stuff and fixes (closing in on an 0.6 release in a week or two).

**Comment by ehazlett** [comment]
Awesome thanks!

**Comment by aalpern** [comment]
The tessera-simple image on dockerhub now has a `development` tag which builds off the current `development` branch in github. The URL path manipulation now uses URI.js's methods instead of dumb string concatenation, so it should be fixed.
