### ISSUE TITLE
Charts does not render on a docker aalpern/tessera-simple deployment

### ISSUE THREAD

**Issue by tzach** [aalpern/docker-tessera-simple#3]
Probably my own fault and not a real bug...
I have a Graphite server running on EC2:

```
sudo docker run --net=host lopter/collectd-graphite
```

I try to add a tessera container on the same server with

```
sudo docker run -P --net=host -e GRAPHITE_URL=http://ip -it aalpern/tessera-simple
```

[For ip I already try EC2 private and public IP, localhost]

I get the dashboard UI working, but there are not charts.
On the browser console I get:

```
GET http://localhost/render?format=json&from=-1h&tz=Etc%2FUTC&target=group%28ab…2%29%29%29&jsonp=jQuery111204286330200266093_1427034471905&_=1427034471906 net::ERR_CONNECTION_REFUSED
```

What am I'm doing wrong?
Why do the browser look for local host?

Thanks

**Comment by tzach** [comment]
I trace the problem down to the Graphite server

```
Traceback (most recent call last):
  File "/opt/graphite/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 126, in renderView
    timestamps = range(series.start, series.end, series.step)
TypeError: range() integer end argument expected, got float.
```

The issue solved once I moved to a more recent Graphite version.

**Comment by aalpern** [comment]
@tzach Glad you got it sorted out! Sorry I've been slow to look into it - I had my hands full getting the latest tessera changes complete before going on vacation :)
